GET http://localhost:8001/users HTTP/1.1
Content-Type: application/json



fetch("http://localhost:8001/prodt")
      .then((res) => res.json())
      .then((prodt) => setlistProducts(prodt))
      .catch((err) => console.log(err))
    // .finally(() => setloaded(false))